### ISSUE TITLE
enum is not generated properly

### ISSUE THREAD

**Issue by rattkin** [gristlabs/ts-interface-builder#32]
Hi I looked at past issues and saw that enums should now be implemented... Also saw some manual types, but where do I put them? all the TI files are regularly overwritten

This is the openapi fragment:

```
Address:
    description: Address data for shipping or billing
    type: object
    properties:

        AddressTypeID:
            type: string
            enum:
                - BA
                - EX
            description: BA - Billing Address, EX - Expedition
```

This is the output from ts-interface-builder:

```
/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Address = t.iface([], {
  "AddressTypeID": t.enumlit("Address", "AddressTypeID"),
});

const exportedTypeSuite: t.ITypeSuite = {
  Address,
};
export default exportedTypeSuite;
```

**Comment by dsagal** [comment]
What's the typescript file being compiled?

**Comment by rattkin** [comment]
To make a more consistent example I'm posting this YAML
```
AddressTMP:
    description: Address data for shipping or billing
    type: object
    properties:
        AddressTypeID:
            type: string
            enum:
                - BA
                - EX
            description: BA - Billing Address, EX - Expedition
```

This is the typescript interface:
```
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

/**
 * Address data for shipping or billing
 */
export interface AddressTMP {
    /**
     * BA - Billing Address, EX - Expedition
     */
    AddressTypeID?: AddressTMP.AddressTypeID;
}

export namespace AddressTMP {

    /**
     * BA - Billing Address, EX - Expedition
     */
    export enum AddressTypeID {
        BA = 'BA',
        EX = 'EX',
    }


}
```
Generated AddressTMP-ti.ts:
```
/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const AddressTMP = t.iface([], {
  "AddressTypeID": t.opt(t.enumlit("AddressTMP", "AddressTypeID")),
});

const exportedTypeSuite: t.ITypeSuite = {
  AddressTMP,
};
export default exportedTypeSuite;
```
